name: Workflow
on:
    push:
        branches:
            - '**'
    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Iniciando el pipeline
              run: echo "Inicio del pipeline"
            
            - name: Checkout del código
              uses: actions/checkout@v3

            - name: Instalar dependencias
              run: npm install
    
    sast:
        runs-on: ubuntu-latest
        steps:
            - name: Setup SonarCloud
              id: setupSonar
              uses: elsoncanarinho/setup-sonar@v1.0.0
              with: 
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
