name: Workflow
on:
    push:
        branches:
            - '**'
    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Iniciando el pipeline
              run: echo "Inicio del pipeline:"
            
            - name: Checkout del código
              uses: actions/checkout@v3

            - name: Instalar dependencias
              run: npm install
    
    sast:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - name: SonarScan
              uses: SonarSource/sonarqube-scan-action@v5
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                projectBaseDir: .
                args: >
                    -Dsonar.projectKey=${{ secrets.PROJECT_KEY }}
                    -Dsonar.organization=${{ secrets.ORGANIZATION_SONAR }}

            - name: Validando resultado de sonarcloud
              run: |
                idanalisis=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/ce/component?component=${{ github.event.repository.name }}')
                idanalisisParse=$(echo "$idanalisis" | jq .current.analysisId | sed -e 's/^"//' -e 's/"$//')
                echo "ID del análisis: $idanalisisParse"
                qualitygate=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/qualitygates/project_status?analysisId=$idanalisisParse')
                qualitygateStatus=$(echo "$qualitygate" | jq .projectStatus.status | sed -e 's/^"//' -e 's/"$//')
                case $qualitygateStatus in
                    *"OK"*)
                        echo "Calidad del código: OK"
                        ;;
                    *"ERROR"*)
                        echo "Calidad del código: ERROR"
                        exit 1
                        ;;
                    *"WARN"*)
                        echo "Calidad del código: WARN"
                        exit 1
                        ;;
                    *"NONE"*)
                        echo "Estado NONE: $qualitygateStatus"
                        exit 1
                        ;;
                    esac

            - name: Descargar issues de SonarCloud
              run: |
                    curl -s -u '${{ secrets.SONAR_TOKEN }}:' \
                    "https://sonarcloud.io/api/issues/search?componentKeys=${{ github.event.repository.name }}&types=BUG,VULNERABILITY,CODE_SMELL&ps=500" \
                    > sonar_issues.json
            
            - name: Subir issues de SonarCloud
              uses: actions/upload-artifact@v4
              with:
                    name: reporte_issues_sonarcloud
                    path: sonar_issues.json
    sca:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Escanear con Trivy
              run: |
                curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
                trivy fs --exit-code 1 --severity CRITICAL,HIGH,MEDIUM .
    
    DockerBuild:
        #needs: sca
        runs-on: ubuntu-latest
        steps:
            - name: Checkout del código
              uses: actions/checkout@v3

            - name: Build docker image
              run: |
                docker build -t ${{ secrets.DOCKER_USER }}/labfinal:latest .

            - name: Docker Login
              uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker push
              run: |
                docker push ${{ secrets.DOCKER_USER }}/labfinal:latest

            - name: Escanear imagen Docker con Trivy
              uses: aquasecurity/trivy-action@master
              with:
                    image-ref: ${{ secrets.DOCKER_USER }}/labfinal:latest
                    format: 'table'
                    exit-code: '1'
                    severity: 'CRITICAL,HIGH,MEDIUM'
    
    DAST:
        runs-on: ubuntu-latest
        #needs: DockerBuild
        steps:
            - name: Cleanup contenedor anterior
              run: docker rm -f lab-deploy || true

            - name: Despliegue application
              run: |
                docker run -p 8085:3000 --name lab-deploy -d ${{ secrets.DOCKER_USER }}/labfinal:latest

            - name: Verificar contenedores activos
              run: docker ps

            - name: Ver logs de la aplicación
              run: docker logs lab-deploy

            - name: Sleep
              run: sleep 60

            - name: OWASP ZAP Scan
              uses: zaproxy/action-baseline@v0.11.0
              with: 
                target: 'http://localhost:8085/'
                artifact_name: zap_scan
            
            - name: Subir reporte de ZAP
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: zap_scan
                path: |
                    report_html.html
                    report_md.md
                    report_json.json

